### PR TITLE
Use raw image as base for nodes & allow k8s release version cluster

### PR DESCRIPTION
**Pull request by robertgzr**
~~Use environment variable `USE_RELEASE=1` on all `kubeadm-nspawn`
commands to spawn a local cluster with the latest k8s release.~~

Use the `--kubernetes-version` flag on the root command set to a **numeric** version
number (e.g. `1.6.5`) to spawn a local cluster with that version.

Not using the flag defaults to spawning a cluster from a local
kubernetes build.

Instead of building a fedora image with `mkosi` we use the raw image specified with the `-i` flag on `kubeadm-nspawn up`.

Needs #44 
Fixes https://github.com/kinvolk/kubeadm-nspawn/issues/9

### CODE REVIEW

**Comment by alban** [comment]
TODO in this PR:
- [ ] update README.md

**Comment by robertgzr** [comment]
what should we keep as todo for this PR now that some items on the list have their own issues?

**Comment by alban** [comment]
@robertgzr I updated my comment to make the distinction.

**Comment by robertgzr** [comment]
Rebased and modified to use a flag instead of an environment variable.

**Comment by robertgzr** [comment]
Rebased after https://github.com/kinvolk/kubeadm-nspawn/commit/b812fa3cf0c7d8515ba3bd495b995fc096fd2cd3

/cc @dongsupark

**Pull request merged**
